"""End-to-end walkthrough of one PestWatch season, stage by stage.

Runs the real pipeline (classifier -> offline sync -> space-time scan -> alerts ->
farmer response) on the dashboard's season and prints the concrete artifact at
each stage: report payloads, scan arithmetic, alert texts, impact. Finishes by
driving the live sync server over HTTP, exactly as the field app does.

Usage: python3 scripts/walkthrough.py [--seed N] [--no-live] [--out docs/END_TO_END.md]
"""
import argparse
import json
import os
import sys
import tempfile
import threading
import urllib.request
from http.server import ThreadingHTTPServer

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import pestwatch  # noqa: E402,F401  (pins BLAS threads before numpy loads)
import numpy as np  # noqa: E402
from pestwatch import i18n  # noqa: E402
from pestwatch.alerts import render, render_sms  # noqa: E402
from pestwatch.farmers import generate_profiles  # noqa: E402
from pestwatch.i18n.inbound import parse  # noqa: E402
from pestwatch.fusion import FusionModel, featurize  # noqa: E402
from pestwatch.messaging import deliver, render_notice  # noqa: E402
from pestwatch.config import CLASSES, TARGET, Config  # noqa: E402
from pestwatch.metrics import compare, first_alert_time  # noqa: E402
from pestwatch.simulation import INSPECTION_REPLY, SCOUT_REPLY  # noqa: E402
from run_demo import load_calibration  # noqa: E402
from pestwatch.simulation import simulate  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")
NAMES = i18n.catalogs()["en"]["ui"]["classes"]


class Doc:
    def __init__(self):
        self.lines = []

    def __call__(self, s=""):
        self.lines.append(s)
        print(s)

    def table(self, header, rows):
        self("| " + " | ".join(header) + " |")
        self("|" + "---|" * len(header))
        for r in rows:
            self("| " + " | ".join(str(x) for x in r) + " |")
        self()


def when(t):
    return f"day {int(t)} {int(round((t % 1) * 24)):02d}:00"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int)
    ap.add_argument("--no-live", action="store_true")
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "END_TO_END.md"))
    a = ap.parse_args()

    cfg = load_calibration(Config())
    seed = a.seed
    scen = os.path.join(ROOT, "web", "data", "scenario.json")
    if seed is None:
        seed = json.load(open(scen))["meta"]["seed"] if os.path.exists(scen) else 0

    pw, cf = simulate(cfg, seed, True), simulate(cfg, seed, False)
    m = compare(pw, cf)
    reg, rep = pw.region, pw.reports
    p, tc, ts, farm, true = pw.p_target, rep["t_cap"], rep["t_sync"], rep["farm"], rep["true_class"]
    vname = lambda f: reg.village_names[reg.farm_village[f]]  # noqa: E731
    label = lambda f: f"Farm {f + 1} ({vname(f)})"  # noqa: E731
    thr = cfg.scan.threshold
    t0 = pw.t_intro
    t_alert = first_alert_time(pw, after=t0)
    d = Doc()

    d("# PestWatch end-to-end walkthrough")
    d()
    d(f"One simulated season (seed {seed}, the same one the dashboard replays), traced through every stage of "
      "the loop: **photo → on-device detection → offline sync → aggregation → outbreak detection → alert → response**. "
      "Generated by `python3 scripts/walkthrough.py`; everything below is real pipeline output on simulated data.")
    d()

    # ---- Stage 0: region
    d("## 0. The region")
    d()
    rows = []
    for v, name in enumerate(reg.village_names):
        fs = np.flatnonzero(reg.farm_village == v)
        rows.append([name, len(fs), int(reg.participates[fs].sum()),
                     f"{reg.online_share[fs[0]]:.0%}", f"{reg.offline_delay_h[fs[0]]:.0f} h",
                     f"{reg.other_damage[fs[0]]:.0%}"])
    d(f"{reg.n_farms} smallholder coffee farms in {len(reg.village_names)} villages over "
      f"{cfg.region.size_km:.0f} × {cfg.region.size_km:.0f} km. Connectivity and background look-alike damage "
      "differ by village.")
    d()
    d.table(["Village", "Farms", "Using app", "Reports syncing instantly", "Mean offline delay",
             "Look-alike damage"], rows)

    # ---- Stage 1: a single photo
    d("## 1. One photo, on the phone")
    d()
    after = (tc >= t0) & np.isin(farm, pw.seed_farms) & (true == TARGET) & (p >= 0.3) & (p < 0.6)
    cand = np.flatnonzero(after & ((ts - tc) * 24 > 6))
    if not len(cand):
        cand = np.flatnonzero(after)
    if not len(cand):
        cand = np.flatnonzero((tc >= t0) & (true == TARGET))
    i = int(cand[0]) if len(cand) else int(np.argmax(p))
    f1 = int(farm[i])
    probs = rep["probs"][i]
    top = int(probs.argmax())
    d(f"On **{when(tc[i])}** the farmer at **{label(f1)}** photographs a coffee leaf. "
      f"(Ground truth, unknown to anyone: the leaf has early rust lesions; "
      f"{pw.damage[int(round(tc[i] / cfg.dt_days)), f1]:.0%} of leaves on this farm are affected.)")
    d()
    d("The on-device model runs offline and returns probabilities:")
    d()
    d.table(["Class", "Probability"], [[NAMES[c] + (" ← top" if k == top else ""), f"{probs[k]:.0%}"]
                                       for k, c in enumerate(CLASSES)])
    verdict = ("likely" if p[i] >= 0.6 else "possible") + " leaf rust"
    if top != TARGET:
        d(f"The model's top guess (*{NAMES[CLASSES[top]]}*) is wrong, as is common on subtle early damage, but it "
          f"still puts {p[i]:.0%} on leaf rust. PestWatch keeps that probability rather than the top label.")
        d()
        verdict = f"{NAMES[CLASSES[top]].lower()}, {probs[top]:.0%} (leaf rust {p[i]:.0%})"
    else:
        verdict += f", {p[i]:.0%}"
    d(f"The app shows *{verdict}*. On its own this is weak evidence; nobody would act on one "
      "uncertain photo. The app queues this payload (the photo itself is never uploaded):")
    d()
    payload = {"id": f"obs-{i}", "farm": f1, "captured_at": when(tc[i]),
               "probs": [round(float(x), 3) for x in probs], "model": "pestwatch-mnv3s-int8"}
    d("```json")
    d(json.dumps(payload))
    d("```")
    d(f"{len(json.dumps(payload))} bytes. The farm has no signal: the report syncs at **{when(ts[i])}**, "
      f"{(ts[i] - tc[i]) * 24:.0f} h later. The server uses the *capture* time for detection, and can only see "
      "the report once it has synced.")
    d()

    # ---- Stage 2: normal background
    d("## 2. Background noise before the outbreak")
    d()
    pre = tc < t0
    n_days = t0
    d(f"In the {n_days:.0f} days before any pest arrives, farmers send {pre.sum():,} photos "
      f"({pre.sum() / n_days:.0f}/day). {int((p[pre] >= 0.5).sum())} of them "
      f"({(p[pre] >= 0.5).mean():.1%}) are flagged as leaf rust with ≥50% confidence, all false flags "
      "(mostly Cercospora / leaf miner look-alikes). The strongest cluster score in this period is "
      f"**{pw.scores[pw.times < t0].max():.2f}** against an alert threshold of **{thr:.2f}**: no alarm.")
    d()
    for e in pw.nuisance:
        in_ev = (tc >= e["start"]) & (tc < e["end"]) & (reg.farm_village[farm] == e["village"])
        base = (tc >= e["start"] - 7) & (tc < e["start"]) & (reg.farm_village[farm] == e["village"])
        k0, k1 = int(e["start"] / cfg.dt_days), int(e["end"] / cfg.dt_days)
        # Strongest cluster centred in the affected village during the event.
        local = [c.llr for evs in pw.top_clusters[k0:k1 + 1] for c in evs
                 if reg.farm_village[c.center_farm] == e["village"]]
        local_max = max(local) if local else 0.0
        infested = int((pw.damage[k0:k1 + 1][:, reg.farm_village == e["village"]] > 0).any(0).sum())
        what = ("Extension training day: photo volume ×%g" % e["multiplier"] if e["kind"] == "engagement_surge"
                else "Look-alike flare-up (Cercospora / leaf miner): damage ×%g" % e["multiplier"])
        verdict = ("no alarm" if local_max < thr else
                   f"alert, but {infested} farms there really were infested by then" if infested else "**false alarm**")
        d(f"- **{what}** in {reg.village_names[e['village']]}, {when(e['start'])}–{when(e['end'])}: "
          f"{in_ev.sum() / (e['end'] - e['start']):.0f} photos/day there vs {base.sum() / 7:.0f}/day the week "
          f"before. Strongest cluster centred there: {local_max:.2f} → {verdict}.")
    d()
    d("Expected counts scale with the photos actually taken and with each farm's own history, so extra photos "
      "or a persistently noisy village don't look like an outbreak.")
    d()

    # ---- Stage 3: the disease arrives
    env = pw.env
    L0 = pw.landings[0]
    d("## 3. The outbreak starts (ground truth)")
    d()
    d(f"On **{when(t0)}**, after the rains, coffee leaf rust spores carried by wind and rain splash arrive near "
      f"{vname(L0.farms[0])} and infect **{len(L0.farms)} farms** over {cfg.pest.landing_days:.0f} days. The first "
      f"lesions cover ~2% of leaves, far below the ~{cfg.pest.visible_threshold:.0%} at which farmers notice rust "
      f"unaided. It is {env.temp[int(t0)]:.0f} °C, close to rust's optimum, and the wind blows towards "
      f"{np.degrees(env.wind_dir[int(t0)]) % 360:.0f}° at {env.wind_speed[int(t0)]:.1f} m/s, so spores drift that way.")
    d()

    # ---- Stage 4: scouting + accumulation
    first_alert_k = int(round(t_alert / cfg.dt_days))
    reqs = [r for r in pw.scout_requests if r["t"] <= t_alert + 1e-9]
    d("## 4. PestWatch asks for evidence: targeted scouting")
    d()
    if reqs:
        r0 = reqs[0]
        trig = next((e for e in pw.top_clusters[int(round(r0["t"] / cfg.dt_days))] if e.cluster_id == r0["cluster_id"]), None)
        why = (f"a trap catch {trig.trap_z:.0f} standard deviations above normal" if trig is not None and trig.trap_led
               else f"a weak photo cluster (scan score {trig.llr:.2f})" if trig is not None else "a watch-level signal")
        d(f"At **{when(r0['t'])}**, {why} near {vname(r0['center_farm'])} puts the area on **watch**. Instead of "
          f"waiting, PestWatch asks the {len(r0['farms'])} nearest farmers to check 10 coffee trees today, in their "
          "own language and channel:")
        d()
        prof0 = generate_profiles(reg, cfg.language, seed)[r0["farms"][0]]
        d(f"> ({i18n.catalogs()[prof0.language]['meta']['native_name']}, {prof0.channel}) "
          f"{render_notice('scout_request', prof0.language, prof0.channel)}")
        d()
    src = rep["src"]
    replies = np.flatnonzero(np.isin(src, [SCOUT_REPLY, INSPECTION_REPLY]) & (ts <= t_alert + 1e-9))
    if len(replies):
        found = p[replies] >= 0.9
        d(f"By the first alert, {len(reqs)} request round(s) went out and **{len(replies)} farmers replied**: "
          f"{int(found.sum())} found rust, {int((~found).sum())} found none. Each reply is strong evidence "
          "(a person looked at 10 trees), and \"none found\" replies are just as useful: they stop false alarms.")
        d()
        d.table(["Farm", "Replied", "Answer", "Truth: farm infested?"],
                [[label(int(farm[j])), when(tc[j]), "rust found" if p[j] >= 0.9 else "none found",
                  "yes" if pw.damage[int(round(tc[j] / cfg.dt_days)), int(farm[j])] > 0 else "no"]
                 for j in replies[np.argsort(tc[replies])][:12]])
    d("Signals per 12 h up to the first alert. *Truth* columns are hidden from the system.")
    d()
    rows, t_mark = [], np.floor(t0)
    while t_mark < t_alert + 1e-9:
        t_next = min(t_mark + 0.5, t_alert)
        kk = int(round(t_next / cfg.dt_days))
        win = (ts > t_mark) & (ts <= t_next)
        lvls = [e.level for e in pw.top_clusters[kk]]
        lvl = "**ALERT**" if "ALERT" in lvls else ("WATCH" if lvls else "–")
        prob = pw.probability[kk] if pw.probability is not None else float("nan")
        rows.append([when(t_next), int((win & (src == 0)).sum()), int((win & (src == 0) & (p >= 0.5)).sum()),
                     int((win & np.isin(src, [SCOUT_REPLY, INSPECTION_REPLY])).sum()),
                     f"{pw.scores[kk]:.2f}", f"{prob:.0%}", int((pw.damage[kk] > 0).sum()),
                     int((pw.damage[kk] >= cfg.pest.visible_threshold).sum()), lvl])
        if t_next >= t_alert:
            break
        t_mark = t_next
    d.table(["Up to", "Photos synced", "Rust ≥50%", "Farmer replies", "Scan score",
             f"P(outbreak) (alert ≥ {cfg.fusion.alert_p:.0%})", "Truth: infested", "Truth: visible", "Level"], rows)

    # ---- Stage 5: detection
    k = first_alert_k
    ev = next(e for e in pw.top_clusters[k] if e.level == "ALERT")
    members = np.flatnonzero(reg.dist[ev.center_farm] <= ev.radius_km)
    fm = FusionModel.load(cfg.fusion.weights_path)
    x = featurize(ev.llr, ev.n_confirmed, ev.trap_z)
    d("## 5. Outbreak detected: fusing the evidence")
    d()
    d(f"At **{when(t_alert)}** ({t_alert - t0:.1f} days after the rust arrived), for a {ev.radius_km} km zone around "
      f"{label(ev.center_farm)} ({len(members)} farms), the fusion model combines:")
    d()
    d.table(["Evidence", "Value", "Weight", "Contribution (log-odds)"],
            [["Photo space-time scan (LLR)", f"{ev.llr:.2f}", f"{fm.w[0]:+.2f}", f"{fm.w[0] * x[0]:+.2f}"],
             ["Farmer confirmations (72 h)", f"{ev.n_confirmed}", f"{fm.w[1]:+.2f} × log(1+n)", f"{fm.w[1] * x[1]:+.2f}"],
             ["Baseline", "", "", f"{fm.bias:+.2f}"]])
    basis = next((a.basis for a in pw.alerts if abs(a.t - t_alert) < 1e-9), "reports")
    forecast = (f" Forecast: at current temperatures ({env.temp[int(t_alert)]:.0f} °C) damage would become visible "
                f"in about **{ev.days_to_visible:.0f} days**." if np.isfinite(ev.days_to_visible) else "")
    d(f"→ **P(outbreak) = {ev.probability:.0%}**, above the alert threshold {cfg.fusion.alert_p:.0%} (calibrated so "
      "at most 10% of outbreak-free seasons ever alert). The alert is **"
      + ("forecast-based" if basis == "traps" else "report-based") + "**." + forecast)
    d()
    vis_now = int((pw.damage[k] >= cfg.pest.visible_threshold).sum())
    d(f"At this moment, {int((pw.damage[k] > 0).sum())} farms are infested but only **{vis_now}** "
      f"show damage a farmer would notice.")
    d()

    # ---- Stage 6: alerts
    profiles = generate_profiles(reg, cfg.language, seed)
    batch = [x for x in pw.alerts if abs(x.t - t_alert) < 1e-9]
    tiers = {r: [x for x in batch if x.risk == r] for r in ("HIGH", "MEDIUM", "LOW")}
    d("## 6. Localized alerts, in each farmer's language and channel")
    d()
    d(f"{len(batch)} farmers get an alert immediately: " + ", ".join(f"{len(v)} {k}" for k, v in tiers.items())
      + f". HIGH = inside the cluster; MEDIUM/LOW = within the {cfg.alert.buffer_km:.0f} km spore-dispersal buffer (stretched downwind). "
      "Report counts are photos with ≥50% leaf rust confidence in the alert area.")
    d()
    d("Each farmer's profile holds a preferred language and channel: app push for smartphone users; SMS or a "
      "voice call (text-to-speech, keypad replies) for feature-phone users. The same alert is rendered from the "
      "message catalog for each recipient:")
    d()
    langs = i18n.languages()
    chans = ("app", "sms", "voice")
    deliveries = [deliver(x, profiles[x.farm]) for x in batch]
    d.table(["Language"] + [c.upper() for c in chans] + ["Total"],
            [[i18n.catalogs()[lg]["meta"]["native_name"]] + [sum(1 for v in deliveries if v.language == lg and v.channel == c)
                                                          for c in chans]
             + [sum(1 for v in deliveries if v.language == lg)] for lg in langs])
    sms_d = [v for v in deliveries if v.channel == "sms"]
    if sms_d:
        d(f"All {len(sms_d)} SMS fit in one GSM-7 segment (≤160 characters, so no Unicode surcharge).")
        d()
    want_channel = {"HIGH": "app", "MEDIUM": "sms", "LOW": "voice"}  # show each channel once
    for r, xs in tiers.items():
        if not xs:
            continue
        early = [x for x in xs if np.isfinite(pw.infected_at[x.farm]) and x.t < pw.infected_at[x.farm] <= x.t + 14]
        early = early or [x for x in xs if not np.isfinite(pw.infected_at[x.farm]) or pw.infected_at[x.farm] > x.t]
        pool = [y for y in xs if profiles[y.farm].channel == want_channel[r]]
        pool = [y for y in pool if y in early] or pool or early or xs
        x = pool[0]
        prof = profiles[x.farm]
        dl = deliver(x, prof)
        fate = ("not yet infested when warned"
                + (f"; pest arrives {pw.infected_at[x.farm] - x.t:.1f} days later" if np.isfinite(pw.infected_at[x.farm]) else "")
                if x in early else "already carrying early, invisible damage")
        d(f"**{r}: {label(x.farm)}**, {fate}. Prefers {i18n.catalogs()[prof.language]['meta']['native_name']} "
          f"by {dl.channel.upper()}" + (f" ({dl.encoding}, {len(dl.text)} chars, {dl.segments} segment)" if dl.channel == "sms" else "") + ":")
        d()
        d(f"> {dl.text}")
        d()
    x = tiers["HIGH"][0] if tiers["HIGH"] else batch[0]
    d(f"The same HIGH alert as each language would deliver it ({label(x.farm)}):")
    d()
    d.table(["", "App", "SMS"], [[i18n.catalogs()[lg]["meta"]["native_name"], render(x, lg), f"`{render_sms(x, lg)}`"]
                                 for lg in langs])

    # ---- Stage 6b: farmer replies
    d("## 7. Farmers reply, in whatever language they write")
    d()
    d("Replies arrive by SMS, in the app, or as keypad presses on the voice call. A keyword grammar built from the "
      "catalogs works offline. It detects the reply's language, handles negation, accents and typos, and answers "
      "in the language the farmer used. A confirmed sighting becomes strong evidence (P(rust) = 0.95) for the scan; "
      "\"none found\" counts as a healthy report. Both also become labels for retraining the vision model.")
    d()
    samples = [(x.farm, "1"), (x.farm, "Nimeona kutu kwenye majani mengi"), (x.farm, "sijaona kutu"),
               (x.farm, "J'ai trouvé de la rouille"), (x.farm, "no rust, all clean"),
               (x.farm, "lugha english"), (x.farm, "STOP")]
    rows = []
    for f, text in samples:
        pr = parse(text, profiles[f].language)
        rows.append([f"`{text}`", i18n.catalogs()[profiles[f].language]["meta"]["native_name"],
                     pr.detected_lang or "–", f"**{pr.intent}**", pr.reply])
    d.table(["Farmer sends", "Profile language", "Detected", "Understood as", "Reply"], rows)

    # ---- Stage 7: response & impact
    d("## 8. Response and outcome")
    d()
    alerted = sorted({x.farm for x in pw.alerts})
    treated_pw = np.isfinite(pw.treated_at)
    early_treat = treated_pw & (pw.treated_at < np.where(np.isfinite(pw.visible_at), pw.visible_at, np.inf))
    d(f"{cfg.response.compliance:.0%} of alerted farmers inspect within 1–4 days (by tier). Inspection finds "
      f"early lesions on infected farms, and control (fungicide and pruning, on extension advice) is applied. Over the season {len(alerted)} farms "
      f"were alerted; {int(early_treat.sum())} farms were treated *before* damage became visible.")
    d()
    d("Same season, same random draws, with and without PestWatch:")
    d()
    rows = [["First warning", when(t_alert), "–"],
            ["First farmer notices damage", "–", when(m["t_first_farmer_notice"]) if m["t_first_farmer_notice"] else "never"],
            ["Extension learns of outbreak (3 farmers + 5-day lag)", "–", when(m["t_conventional"]) if m["t_conventional"] else "–"],
            ["Widespread (10% of farms visibly damaged)", "–", when(m["t_widespread"]) if m["t_widespread"] else "not reached"],
            ["Farms ever infested", m["farms_infested_pw"], m["farms_infested_cf"]],
            ["Farms visibly damaged at season end", m["farms_visible_end_pw"], m["farms_visible_end_cf"]],
            ["Yield loss", f"${m['loss_pw']['yield_loss_usd']:,.0f}", f"${m['loss_cf']['yield_loss_usd']:,.0f}"],
            ["Treatment cost", f"${m['loss_pw']['treatment_cost_usd']:,.0f}", f"${m['loss_cf']['treatment_cost_usd']:,.0f}"]]
    d.table(["", "With PestWatch", "Without"], rows)
    d(f"**Lead time:** {m['lead_vs_conventional_days']:.1f} days ahead of the conventional route, "
      + (f"{m['lead_vs_widespread_days']:.1f} days before widespread infestation. " if m["lead_vs_widespread_days"] else "")
      + f"**Recall:** {m['recall']:.0%} of infested farms warned before visible damage. "
      f"**Precision:** {m['precision_HIGH']:.0%} of HIGH-alerted farms infested within 14 days "
      f"({m['precision_all']:.0%} across all tiers). **Crop loss avoided:** ${m['loss_avoided_usd']:,.0f} "
      f"({m['loss_avoided_pct']:.0%} of yield loss) for this region-season.")
    d()
    d("**Keeping farmers' trust (alert fatigue).** "
      f"Each farmer received {m['alerts_per_farm_mean']:.1f} alerts on average over the season (max "
      f"{m['alerts_per_farm_max']}); {m['alerts_suppressed_by_budget']} lower-priority alerts were held back by the "
      f"budget of {cfg.alert.max_alerts_per_14d} per fortnight (HIGH escalations always go through). Alert zones are "
      f"stretched downwind and shortened upwind, with the same area as a circle. When an area stays quiet for "
      f"{cfg.alert.all_clear_days:.0f} days, farmers get an all-clear ({m['all_clear_messages']} sent):")
    d()
    clear = next((n for n in pw.notices if n.kind == "all_clear"), None)
    if clear:
        pc_ = profiles[clear.farm]
        d(f"> ({i18n.catalogs()[pc_.language]['meta']['native_name']}, {pc_.channel}) "
          f"{render_notice('all_clear', pc_.language, pc_.channel, clear.days)}")
        d()
    high_zone = [a_.farm for a_ in pw.alerts if a_.risk == "HIGH" and abs(a_.t - t_alert) < 1e-9]
    ha = float(reg.farm_ha[high_zone].sum()) if high_zone else 0.0
    d("**For extension services and agro-dealers.** At the first alert the HIGH zone covers "
      f"{len(high_zone)} farms / {ha:.0f} ha, so about **{ha * cfg.response.control_dose_l_per_ha:.0f} L** of "
      "copper fungicide (an assumed dose) should be pre-positioned at the nearest agro-dealer or cooperative.")
    if pw.triggers:
        tr0 = pw.triggers[0]
        d(f" At {when(tr0['t'])} the fused probability reached {tr0['probability']:.0%} with ≥"
          f"{cfg.fusion.trigger_min_farms} farms reporting, which fires the **anticipatory-finance trigger**: "
          f"{tr0['farms_at_risk']} farms / {tr0['ha_at_risk']:.0f} ha at risk → ${tr0['payout_usd']:,.0f} released "
          f"for control inputs (at ${cfg.response.finance_usd_per_ha:.0f}/ha, an assumed rate).")
    d()
    c_ = m["cost"]
    d(f"**Cost.** Running PestWatch here this season costs about **${c_['total']:,.0f}** "
      f"(${c_['per_farm']:.2f} per farm): messaging ${c_['messaging']:,.0f}, platform ${c_['platform']:,.0f}, "
      f"lead-farmer stipends ${c_['lead_farmers']:,.0f}, extension visits "
      f"${c_['extension_visits']:,.0f}. Against ${m['loss_avoided_usd']:,.0f} of yield loss avoided that is a "
      f"**benefit-cost ratio of {m['benefit_cost_ratio']:.0f}×** (unit costs are assumptions in `CostConfig`).")
    d()

    # ---- Stage 8: live
    if not a.no_live:
        live_section(d, label)

    d("---")
    d("Simulated region, pest dynamics, farmer behaviour and model outputs; parameters in `pestwatch/config.py`. "
      "Across 60 seasons see `reports/EVALUATION.md`.")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as f:
        f.write("\n".join(d.lines) + "\n")
    print(f"\n[written to {os.path.relpath(a.out, ROOT)}]", file=sys.stderr)


def live_section(d, label):
    """Drive the real sync server over HTTP, the way the field app does."""
    import server
    from pestwatch.service.gateways import ConsoleGateway
    tmp = tempfile.mkdtemp()
    # Temporary DB and a silent gateway, so the demo's own data is untouched.
    server.Handler.state = server.LiveState(db_path=os.path.join(tmp, "walkthrough.db"),
                                            gateway=ConsoleGateway(stream=open(os.devnull, "w")),
                                            admin_key="walkthrough")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), server.Handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    base = f"http://127.0.0.1:{httpd.server_address[1]}"

    def call(path, body=None):
        req = urllib.request.Request(base + path, data=None if body is None else json.dumps(body).encode(),
                                     headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read())

    farms = call("/api/farms")["farms"]
    f = next((x for x in farms if x["suggested"] and x["app"]), next(x for x in farms if x["app"]))["id"]
    before = call(f"/api/status?farm={f}")
    d("## 9. The same loop, live over HTTP")
    d()
    d(f"`server.py` freezes this season at **day {before['t_live']}**, one step before the first alert, and "
      "accepts reports from the field app. This section was produced by actually calling it.")
    d()
    c = before["clusters"][0] if before["clusters"] else None
    d(f"`GET /api/status?farm={f}` → "
      + (f"**{c['level']}** near {c['village']}: P(outbreak) {c['probability']:.1%} (alert at "
         f"{c['alert_probability']:.1%}; scan score {c['llr']}), "
         f"{c['n_reports']} reports from {c['n_farms']} farms; no alert for {label(f)}." if c else "quiet."))
    d()
    obs = {"id": "walkthrough-1", "farm": f, "captured_at": "now", "model": "demo-stub-v0",
           "probs": [0.28, 0.50, 0.04, 0.15, 0.03]}
    d(f"The farmer at {label(f)} photographs a leaf with faint spots (model: *possible* leaf rust, 50%). "
      "After the phone regains signal it posts:")
    d()
    d("```")
    d(f"POST /api/observations  {json.dumps({'observations': [obs]})}")
    d("```")
    after = call("/api/observations", {"observations": [obs]})
    c2 = after["clusters"][0] if after["clusters"] else None
    d(f"Response: cluster is now **{c2['level']}**, P(outbreak) {c2['probability']:.1%} "
      f"(was {c['probability'] if c else 0:.1%}). "
      if c2 else "Response: no cluster. ")
    if after["alert"]:
        al = after["alert"]
        dl = al["delivery"]
        d(f"The response carries this farmer's alert ({al['risk']}), rendered for their profile "
          f"({dl['language']}, {dl['channel']}):")
        d()
        d(f"> {dl['text']}")
    else:
        d("No alert for this farm yet; more reports from the area would be needed.")
    d()
    msg = {"farm": f, "text": "Nimeona kutu kwenye majani ya kahawa", "channel": "sms"}
    d("After inspecting, the farmer replies by SMS in Swahili, although their profile is "
      f"{after['profile']['language']}:")
    d()
    d("```")
    d(f"POST /api/inbound  {json.dumps(msg, ensure_ascii=False)}")
    d("```")
    r = call("/api/inbound", msg)
    d(f"→ understood as **{r['intent']}** (detected `{r['detected_lang']}`, matched {', '.join(r['matched'])}); "
      f"reply in {r['reply_lang']}: *{r['reply']}* The confirmation is added to the scan as a high-confidence report.")
    d()
    r = call("/api/inbound", {"farm": f, "text": "Kiswahili"})
    st = call(f"/api/status?farm={f}")
    d(f"They then text `Kiswahili`, so their profile language becomes `{r['profile']['language']}` and future alerts "
      + (f"arrive in Swahili: *{st['alert']['delivery']['text'][:110]}…*" if st["alert"] else "arrive in Swahili."))
    d()
    httpd.shutdown()


if __name__ == "__main__":
    main()
